32. Используя модуль array и библиотеку numpy, решить следующие задачи:
а) Дан целочисленный массив размера  N . Найти максимальное количество его одинаковых элементов.
б) Дана целочисленная матрица размера  M×N . Найти количество ее столбцов, все элементы которых различны.

In [4]:
import numpy as np

def max_equal_elements(arr):
    unique, counts = np.unique(arr, return_counts=True)
    max_count = max(counts)
    return max_count

N = 10
arr = np.random.randint(0, 5, N)
result = max_equal_elements(arr)
print(arr, result)

[0 4 0 1 2 1 2 4 2 2] 4


In [10]:
def count_columns_with_unique_elements(matrix):
    num_unique = np.sum([len(set(col)) == matrix.shape[0] for col in matrix.T])
    return num_unique

M, N = 5, 5
matrix = np.random.randint(0, 10, (M, N))
result = count_columns_with_unique_elements(matrix)
print(matrix, result)

[[8 6 6 1 9]
 [9 9 5 9 0]
 [4 0 9 3 1]
 [4 7 5 1 9]
 [9 8 7 1 8]] 1


33. Дан стек и два элемента  A  и  B . Необходимо удалить из стека все элементы, которые находятся между  A  и  B  (включая сами  A  и  B ).

In [16]:
def remove_elements_between(stack, A, B):
    if A not in stack or B not in stack:
        return "Один из элементов A или B отсутствует в стеке"

    start_index = stack.index(A)
    end_index = stack.index(B)
    if start_index > end_index:
        start_index, end_index = end_index, start_index

    stack = stack[:start_index] + stack[end_index + 1:]
    return stack


stack = [1, 2, 3, 4, 5, 6, 7, 8, 9]
A = 2
B = 5
new_stack = remove_elements_between(stack, A, B)
print(new_stack)

[1, 6, 7, 8, 9]


34 Создать класс очереди, который будет поддерживать операции добавления элемента в конец очереди, удаления элемента из начала очереди и поиска минимального элемента в очереди.

In [19]:
from collections import deque

class MinQueue:
    def __init__(self):
        self.queue = deque()
    
    def enqueue(self, item):     # добавление эл-а в конец очереди
        self.queue.append(item)
    
    def dequeue(self):           # удалние эл-а из начала очереди
        if not self.queue:
            return None
        return self.queue.popleft()
    
    def find_min(self):          # поиск минимального эл-а в очереди
        if not self.queue:
            return None
        return min(self.queue)

q = MinQueue()
q.enqueue(1)
q.enqueue(3)
q.enqueue(4)
q.enqueue(2)
print('минимальный эл-т в изначальной очереди', q.find_min())
q.dequeue()  # удалим эл-т из начала очереди
print('минимальный эл-т после удаления первого эл-та', q.find_min()) 

минимальный эл-т в изначальной очереди 1
минимальный эл-т после удаления первого эл-та 2
